name: google_provider
description: Google Provider
version: 0.0.6
repository: https://github.com/tiki/google_provider
publish_to: none # package in active development

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^2.4.0
  httpp:
    git:
      url: https://github.com/tiki/httpp
      ref: 0.0.3
  info_carousel:
    git:
      url: https://github.com/tiki/info_carousel
      ref: 0.0.4
  logging: ^1.0.2
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  assets:
    - res/images/