name: google_provider
description: Google provider for TIKI
version: 0.0.9
homepage: https://mytiki.com
repository: https://github.com/tiki/google_provider
issue_tracker: https://github.com/tiki/google_provider/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  flutter_appauth: ^2.4.0
  httpp: ^0.0.4
  info_carousel: ^0.0.4
  logging: ^1.0.2
  provider: ^6.0.2
  tiki_style: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# this is a development credential
false_secrets:
  - lib/src/google_provider_service.dart
