name: tiki_strategy_google
description: Google integration strategy for TIKI
version: 0.1.11
homepage: https://mytiki.com
repository: https://github.com/tiki/strategy_google
issue_tracker: https://github.com/tiki/strategy_google/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  flutter_appauth: ^4.0.1
  httpp: ^0.0.6
  info_carousel: ^0.0.7
  logging: ^1.0.2
  provider: ^6.0.3
  tiki_style: ^0.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


false_secrets:
  - example/lib/main.dart